### ISSUE TITLE
KeyError while compiling font with --color_format=picosvg

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/nanoemoji#129]
After https://github.com/googlefonts/nanoemoji/pull/125 PR was merged (released in v0.3.2), attempting to compile either noto-emoji or twemoji with --color_format=picosvg fails with this error:

```
I0918 15:26:01.156373 4828491200 write_font.py:203] Writing /Users/clupo/Github/color-fonts/fonts/twemoji-picosvg.ttf
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/clupo/Github/nanoemoji/src/nanoemoji/write_font.py", line 504, in <module>
    app.run(main)
  File "/Users/clupo/Github/color-fonts/venv/lib/python3.8/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/Users/clupo/Github/color-fonts/venv/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/Users/clupo/Github/nanoemoji/src/nanoemoji/write_font.py", line 499, in main
    _write(ufo, ttfont, FLAGS.output_file)
  File "/Users/clupo/Github/nanoemoji/src/nanoemoji/write_font.py", line 208, in _write
    ttfont.save(output_file)
  File "/Users/clupo/Github/fonttools/Lib/fontTools/ttLib/ttFont.py", line 172, in save
    writer_reordersTables = self._save(tmp)
  File "/Users/clupo/Github/fonttools/Lib/fontTools/ttLib/ttFont.py", line 211, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/Users/clupo/Github/fonttools/Lib/fontTools/ttLib/ttFont.py", line 628, in _writeTable
    self._writeTable(masterTable, writer, done, tableCache)
  File "/Users/clupo/Github/fonttools/Lib/fontTools/ttLib/ttFont.py", line 632, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Users/clupo/Github/fonttools/Lib/fontTools/ttLib/ttFont.py", line 650, in getTableData
    return self.tables[tag].compile(self)
  File "/Users/clupo/Github/fonttools/Lib/fontTools/ttLib/tables/_m_a_x_p.py", line 44, in compile
    self.recalc(ttFont)
  File "/Users/clupo/Github/fonttools/Lib/fontTools/ttLib/tables/_m_a_x_p.py", line 77, in recalc
    g = glyfTable[glyphName]
  File "/Users/clupo/Github/fonttools/Lib/fontTools/ttLib/tables/_g_l_y_f.py", line 240, in __getitem__
    glyph = self.glyphs[glyphName]
KeyError: 'a9'
```

I believe I know what's going on and have a fix coming, stay tuned.

**Comment by anthrotype** [comment]
The problem only occurs when `keep_glyph_names` option is False, which is the default on the command line, however in the tests we default to True so that the ttx files contain more meaningful/debug-able glyph names.
Also, in the tests we were dumping the generated TTFont straight to TTX (for comparisong against for expected TTX) but this issue only occurs when compiling the font (ie. saving binary font to disk). Doing a TTFont.save onto a temporary stream and reloading a new instance from it manages to reproduce the error. I just did that on master, no other changes to the actual tests, see error here
https://travis-ci.org/github/googlefonts/nanoemoji/builds/728394836

The problem is the glyph names in the TTFont were we add the SVG table may have been dropped (with --nokeep_glyph_names the post table version is set to 3.0, effectively dropping the names), so the
names we see after decompiling it are made up by fonttools and different from the input color glyph names.
In _ensure_groups_grouped_in_glyph_order, we want to reorder the glyphs but we also end up involuntarily renaming them as we use the old color glyph names. Of course we can't change order and rename at the same time, otherwise tables that contain mappings keyed by glyph name would blow up upon compiling the TTFont (like in the error above with 'glyf').

To fix this, we need to match the old and current names by their position in the font current glyph order: i.e. we assume all color glyphs are placed at the `END` of the glyph order -- which is where we place them earlier in the pipeline when we create the empty placeholder color glyphs.

I'll send a PR to fix this shortly.
