### ISSUE TITLE
struct.error while compiling 'COLR' table on SVG created with Figma

### ISSUE THREAD

**Issue by paullinnerud** [googlefonts/nanoemoji#243]
Running "nanoemoji --color_format glyf_colr_1 emoji_u1f46b.svg" on Mac

struct.error when compiling 'COLR' table. 

Attached SVG file. I noticed this SVG uses absolute coordinates. Is that a problem?

thanks, 
Paul

I0226 10:52:23.632082 4669390336 ttFont.py:649] compiling 'COLR' table
Traceback (most recent call last):
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/paulli/projects/emoji_dev/nanoemoji/src/nanoemoji/write_font.py", line 508, in <module>
    app.run(main)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/Users/paulli/projects/emoji_dev/nanoemoji/src/nanoemoji/write_font.py", line 502, in main
    ufo, ttfont = _generate_color_font(font_config, inputs)
  File "/Users/paulli/projects/emoji_dev/nanoemoji/src/nanoemoji/write_font.py", line 468, in _generate_color_font
    ttfont = _make_ttfont(config, ufo, color_glyphs)
  File "/Users/paulli/projects/emoji_dev/nanoemoji/src/nanoemoji/write_font.py", line 171, in _make_ttfont
    ttfont = ufo2ft.compileTTF(ufo, overlapsBackend="pathops")
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/ufo2ft/__init__.py", line 236, in compileTTF
    postProcessor = PostProcessor(otf, ufo, glyphSet=glyphSet)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/ufo2ft/postProcessor.py", line 45, in __init__
    otf.save(stream)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 172, in save
    writer_reordersTables = self._save(tmp)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 211, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 632, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 650, in getTableData
    return self.tables[tag].compile(self)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/fontTools/ttLib/tables/C_O_L_R_.py", line 83, in compile
    table.compile(writer, ttFont)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 735, in compile
    conv.write(writer, font, table, value)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 565, in write
    value.compile(subWriter, font)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 698, in compile
    conv.write(writer, font, table, value, i)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 565, in write
    value.compile(subWriter, font)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 735, in compile
    conv.write(writer, font, table, value)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 565, in write
    value.compile(subWriter, font)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 735, in compile
    conv.write(writer, font, table, value)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 444, in write
    value.compile(writer, font)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 735, in compile
    conv.write(writer, font, table, value)
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 360, in write
    writer.writeLong(fl2fi(value, 16))
  File "/Users/paulli/.virtualenvs/emoji_dev_env/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 445, in writeLong
    self.items.append(struct.pack(">l", value))
struct.error: ("'l' format requires -2147483648 <= number <= 2147483647", 'float', 'Affine2x3', 'Paint', 'Paint[0]', 'LayerV1List')

[emoji_u1f46b.svg.zip](https://github.com/googlefonts/nanoemoji/files/6051815/emoji_u1f46b.svg.zip)

**Comment by paullinnerud** [comment]
I was experimenting with the SVG that fails to try and reduce it further. The following SVG fails to build into a font. 

<svg width="384" height="384" viewBox="0 0 384 384" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="64" cy="64" r="60" fill="url(#paint2_radial)"/>
<defs>
<radialGradient id="paint2_radial" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(297 103) rotate(123.286) scale(393.57)">
<stop stop-color="#FFE253"/>
<stop offset="0.725736" stop-color="#DF8529"/>
<stop offset="1" stop-color="#FF8C00"/>
</radialGradient>
</defs>
</svg>

However if I remove the scale in the gradient transformation, it works. 

<svg width="384" height="384" viewBox="0 0 384 384" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="64" cy="64" r="60" fill="url(#paint2_radial)"/>
<defs>
<radialGradient id="paint2_radial" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(297 103) rotate(123.286)">
<stop stop-color="#FFE253"/>
<stop offset="0.725736" stop-color="#DF8529"/>
<stop offset="1" stop-color="#FF8C00"/>
</radialGradient>
</defs>
</svg>

Does that make sense?

**Comment by yisibl** [comment]
```svg
<svg width="384" height="384" viewBox="0 0 384 384" fill="none" xmlns="http://www.w3.org/2000/svg">
	    <defs>
        <radialGradient id="paint0_radial" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(36 180) rotate(110.556) scale(68.352)">
            <stop stop-color="#EC8819" />
            <stop offset="1" stop-color="#EE8917" />
        </radialGradient>
        <radialGradient id="paint1_radial" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(348 184) rotate(66.8014) scale(91.3893 136.228)">
            <stop stop-color="#FBD14B" />
            <stop offset="1" stop-color="#F8A221" />
        </radialGradient>
        <radialGradient id="paint2_radial" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(297 103) rotate(123.286) scale(393.57)">
            <stop stop-color="#FFE253" />
            <stop offset="0.725736" stop-color="#DF8529" />
            <stop offset="1" stop-color="#FF8C00" />
        </radialGradient>
    </defs>
    <path d="M0 200C0 182.327 14.3269 168 32 168H40V232H32C14.3269 232 0 217.673 0 200Z" fill="url(#paint0_radial)" />
    <path d="M384 200C384 182.327 369.673 168 352 168H344V232H352C369.673 232 384 217.673 384 200Z" fill="url(#paint1_radial)" />
    <path d="M32 192C32 184.572 32 180.858 32.1298 177.719C35.3979 98.7054 98.7054 35.3979 177.719 32.1298C180.858 32 184.572 32 192 32C199.428 32 203.142 32 206.281 32.1298C285.295 35.3979 348.602 98.7054 351.87 177.719C352 180.858 352 184.572 352 192C352 199.428 352 203.142 351.87 206.281C348.602 285.295 285.295 348.602 206.281 351.87C203.142 352 199.428 352 192 352C184.572 352 180.858 352 177.719 351.87C98.7054 348.602 35.3979 285.295 32.1298 206.281C32 203.142 32 199.428 32 192Z" fill="url(#paint2_radial)" />
</svg>
```

Exactly 1 <defs> element, first child of root

**Comment by anthrotype** [comment]
thanks @paullinnerud for the report and for attaching a test file that reproduces this.
I'm looking it it. One thing I noticed is the file contain radialGradients where the centre and radius is that of a unitary circle at (0,0) and then all the task of positioning/scaling the gradient is performed by a gradientTransform matrix with some relatively large numbers; when nanoemoji has to map the viewBox units onto the font UPEMs, the additional scaling makes such that the Affine2x3 values are too big to fit the Fixed16.16 bounds and thus we get the struct.error (which is like an overflow error).
Maybe our tool should pre-apply some of that gradientTransform to the gradient circles and only encode the part of the matrix that turns these into ellipses (if any).

**Comment by paullinnerud** [comment]
Thanks, that gradient record was created with the tool Figma which is what I believe the team is using to create the SVG data.

**Comment by anthrotype** [comment]
@paullinnerud your SVGs from Figma should work now with the latest nanoemoji/picosvg, please let me know if you still have problems, thanks!

**Comment by paullinnerud** [comment]
It seems to work, thanks so much.
