### ISSUE TITLE
Error compiling noto with waved flags

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/nanoemoji#245]
Use the wave-flags branch of https://github.com/googlefonts/color-fonts. Run `time nanoemoji --config config/noto-glyf_colr_1.toml`:

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "venv/lib/python3.8/site-packages/nanoemoji/write_font.py", line 508, in <module>
    app.run(main)
  File "venv/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "venv/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "venv/lib/python3.8/site-packages/nanoemoji/write_font.py", line 502, in main
    ufo, ttfont = _generate_color_font(font_config, inputs)
  File "venv/lib/python3.8/site-packages/nanoemoji/write_font.py", line 468, in _generate_color_font
    ttfont = _make_ttfont(config, ufo, color_glyphs)
  File "venv/lib/python3.8/site-packages/nanoemoji/write_font.py", line 171, in _make_ttfont
    ttfont = ufo2ft.compileTTF(ufo, overlapsBackend="pathops")
  File "venv/lib/python3.8/site-packages/ufo2ft/__init__.py", line 236, in compileTTF
    postProcessor = PostProcessor(otf, ufo, glyphSet=glyphSet)
  File "venv/lib/python3.8/site-packages/ufo2ft/postProcessor.py", line 45, in __init__
    otf.save(stream)
  File "venv/lib/python3.8/site-packages/fontTools/ttLib/ttFont.py", line 172, in save
    writer_reordersTables = self._save(tmp)
  File "venv/lib/python3.8/site-packages/fontTools/ttLib/ttFont.py", line 211, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "venv/lib/python3.8/site-packages/fontTools/ttLib/ttFont.py", line 632, in _writeTable
    tabledata = self.getTableData(tag)
  File "venv/lib/python3.8/site-packages/fontTools/ttLib/ttFont.py", line 650, in getTableData
    return self.tables[tag].compile(self)
  File "venv/lib/python3.8/site-packages/fontTools/ttLib/tables/C_O_L_R_.py", line 83, in compile
    table.compile(writer, ttFont)
  File "venv/lib/python3.8/site-packages/fontTools/ttLib/tables/otBase.py", line 735, in compile
    conv.write(writer, font, table, value)
  File "venv/lib/python3.8/site-packages/fontTools/ttLib/tables/otConverters.py", line 577, in write
    value.compile(subWriter, font)
  File "venv/lib/python3.8/site-packages/fontTools/ttLib/tables/otBase.py", line 698, in compile
    conv.write(writer, font, table, value, i)
  File "venv/lib/python3.8/site-packages/fontTools/ttLib/tables/otConverters.py", line 577, in write
    value.compile(subWriter, font)
  File "venv/lib/python3.8/site-packages/fontTools/ttLib/tables/otBase.py", line 735, in compile
    conv.write(writer, font, table, value)
  File "venv/lib/python3.8/site-packages/fontTools/ttLib/tables/otConverters.py", line 577, in write
    value.compile(subWriter, font)
  File "venv/lib/python3.8/site-packages/fontTools/ttLib/tables/otBase.py", line 735, in compile
    conv.write(writer, font, table, value)
  File "venv/lib/python3.8/site-packages/fontTools/ttLib/tables/otConverters.py", line 253, in write
    writer.writeShort(value)
  File "venv/lib/python3.8/site-packages/fontTools/ttLib/tables/otBase.py", line 428, in writeShort
    assert -32768 <= value < 32768, value
AssertionError: (57168, 'int', 'Paint', 'Paint[4325]', 'LayerV1List')
```

May be an input issue but if it is we should have caught it earlier and expressed our concern more clearly.

**Comment by rsheeter** [comment]
Sport of bad gradients continues? - also ... this data dump makes me think we might be missing some rounding

```
PaintedLayer(paint=PaintLinearGradient(extend=<Extend.PAD: (0,)>, stops=(), p0=Point(x=57168.30599807032, y=-67463.14734591146), p1=Point(x=51292.76083025834, y=-64912.76031255208), p2=Point(x=58256.25852533959, y=-53689.647276458345)

PaintedLayer(paint=PaintLinearGradient(extend=<Extend.PAD: (0,)>, stops=(), p0=Point(x=57168.30599807032, y=-67463.14734591146), p1=Point(x=51292.76083025834, y=-64912.76031255208), p2=Point(x=58256.25852533959, y=-53689.647276458345))
```

**Comment by rsheeter** [comment]
Looks to me like a bad gradient (missing userSpaceOnUse?) in objectBoundingBox space ends up getting scaled up quite considerably and ends up with out of bounds units.

```
    <linearGradient id="grad2" xlink:href="#gradbase" x1="851.56865" y1="436.06697" x2="763.03312" y2="419.67318"/>

Prior to conversion from objectBoundingBox p0 p1 p2:
    Point(x=851.56865, y=436.06697)
    Point(x=763.03312, y=419.67318)
    Point(x=867.96244, y=347.53144000000003)

After conversion:
    Point(x=57168.30599807032, y=-67463.14734591146)
    Point(x=51292.76083025834, y=-64912.76031255208)
    Point(x=58256.25852533959, y=-53689.647276458345)
```

We should either raise an error in gradient processing or convert this to the effective rendering (such as a solid pad color).

**Comment by anthrotype** [comment]
about emoji_u1f1eb_1f1f0.svg, the problem seems to be picosvg is ignoring the `xlink:href` attributes in those gradients, see: https://github.com/googlefonts/picosvg/issues/191

**Comment by rsheeter** [comment]
I hadn't even realized that was possible lol
