### ISSUE TITLE
Generation of picosvg font fails if a composite is encountered

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/nanoemoji#315]
```
# in https://github.com/googlefonts/color-fonts
nanoemoji --config config/noto_noflags-picosvg.toml
I0804 18:48:29.073715 139698156504896 nanoemoji.py:312] Wrote color-fonts/build/config.toml
I0804 18:48:29.074158 139698156504896 nanoemoji.py:338] Generating build.ninja
I0804 18:48:30.251909 139698156504896 nanoemoji.py:366] ninja -C color-fonts/build
ninja: Entering directory `color-fonts/build'
[3323/3323] color-fonts/venv/bin/python3 -m nanoemoji.write_font -v 0  --config config.toml @noto_noflags-picosvg.ttf.rsp
FAILED: noto_noflags-picosvg.ttf 
color-fonts/venv/bin/python3 -m nanoemoji.write_font -v 0  --config config.toml @noto_noflags-picosvg.ttf.rsp
I0804 18:49:22.683311 140083813922624 __init__.py:213] Pre-processing glyphs
I0804 18:49:22.701976 140083813922624 base.py:178] Running DecomposeComponentsFilter on noto_noflags-picosvg-Regular
I0804 18:49:22.703180 140083813922624 base.py:178] Running CubicToQuadraticFilter on noto_noflags-picosvg-Regular
I0804 18:49:22.704444 140083813922624 __init__.py:234] Building OpenType tables
I0804 18:49:23.219351 140083813922624 postProcessor.py:279] Setting post.formatType = 3.0
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "nanoemoji/src/nanoemoji/write_font.py", line 653, in <module>
    app.run(main)
  File "color-fonts/venv/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "color-fonts/venv/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "nanoemoji/src/nanoemoji/write_font.py", line 647, in main
    ufo, ttfont = _generate_color_font(font_config, inputs)
  File "nanoemoji/src/nanoemoji/write_font.py", line 613, in _generate_color_font
    ttfont = _make_ttfont(config, ufo, color_glyphs)
  File "nanoemoji/src/nanoemoji/write_font.py", line 216, in _make_ttfont
    _COLOR_FORMAT_GENERATORS[config.color_format].apply_ttfont(
  File "nanoemoji/src/nanoemoji/write_font.py", line 122, in <lambda>
    lambda *args: _svg_ttfont(*args, picosvg=True, compressed=False),
  File "nanoemoji/src/nanoemoji/write_font.py", line 565, in _svg_ttfont
    make_svg_table(config, ttfont, color_glyphs, picosvg, compressed)
  File "nanoemoji/src/nanoemoji/svg.py", line 547, in make_svg_table
    doc_list = _picosvg_docs(config, ttfont, color_glyphs)
  File "nanoemoji/src/nanoemoji/svg.py", line 482, in _picosvg_docs
    _add_glyph(svg, color_glyph, reuse_cache)
  File "nanoemoji/src/nanoemoji/svg.py", line 399, in _add_glyph
    raise ValueError(f"What do we do with {context}")
ValueError: What do we do with PaintTraverseContext(path=(), paint=PaintComposite(mode=<CompositeMode.SRC_IN: 5>, source=PaintColrLayers(layers=(PaintGlyph(glyph='M97.72,44.18 C99.03,44.18 100.09,45.36 100.09,46.82 C100.09,48.27 99.03,49.46 97.72,49.46 C96.41,49.46 95.35,48.28 95.35,46.82 C95.35,45.36 96.41,44.18 97.72,44.18 M97.72,42.18 C95.31,42.18 93.35,44.26 93.35,46.82 C93.35,49.38 95.31,51.46 97.72,51.46 C100.13,51.46 102.09,49.38 102.09,46.82 C102.09,44.26 100.13,42.18 97.72,42.18 Z', paint=PaintSolid(color=Color(red=66, green=66, blue=66, alpha=1.0))), PaintGlyph(glyph='M30.78,44.18 C32.09,44.18 33.15,45.36 33.15,46.82 C33.15,48.27 32.09,49.46 30.78,49.46 C29.47,49.46 28.41,48.28 28.41,46.82 C28.42,45.36 29.48,44.18 30.78,44.18 M30.78,42.18 C28.37,42.18 26.41,44.26 26.41,46.82 C26.41,49.38 28.37,51.46 30.78,51.46 C33.19,51.46 35.15,49.38 35.15,46.82 C35.15,44.26 33.2,42.18 30.78,42.18 Z', paint=PaintSolid(color=Color(red=66, green=66, blue=66, alpha=1.0))), PaintGlyph(glyph='M63.85,18.5 C65.16,18.5 66.22,19.68 66.22,21.14 C66.22,22.59 65.16,23.78 63.85,23.78 C62.54,23.78 61.48,22.6 61.48,21.14 C61.48,19.68 62.54,18.5 63.85,18.5 M63.85,16.5 C61.44,16.5 59.48,18.58 59.48,21.14 C59.48,23.7 61.44,25.78 63.85,25.78 C66.26,25.78 68.22,23.7 68.22,21.14 C68.22,18.58 66.26,16.5 63.85,16.5 Z', paint=PaintSolid(color=Color(red=66, green=66, blue=66, alpha=1.0))))), backdrop=PaintSolid(color=Color(red=0, green=0, blue=0, alpha=0.2))), transform=Affine2D(a=1, b=0, c=0, d=1, e=0, f=0))
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "color-fonts/venv/bin/nanoemoji", line 11, in <module>
    load_entry_point('nanoemoji', 'console_scripts', 'nanoemoji')()
  File "nanoemoji/src/nanoemoji/nanoemoji.py", line 376, in main
    app.run(_run)
  File "color-fonts/venv/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "color-fonts/venv/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "nanoemoji/src/nanoemoji/nanoemoji.py", line 367, in _run
    subprocess.run(ninja_cmd, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-C', 'color-fonts/build']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "color-fonts/build.py", line 61, in <module>
    main()
  File "color-fonts/build.py", line 50, in main
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('nanoemoji', '--config', 'config/noto_noflags-picosvg.toml')' returned non-zero exit status 1.
```

**Comment by rsheeter** [comment]
Notably, `_painted_layers` in color_glyph.py can produce a PaintComposite that will then fail to become a picosvg.
