### ISSUE TITLE
ValueError: invalid or unsupported color string: 'currentColor'

### ISSUE THREAD

**Issue by Theelx** [googlefonts/nanoemoji#380]
When building a COLRv1 font out of any SVG using fill="currentColor", nanoemoji raises `ValueError: invalid or unsupported color string: 'currentColor'`. However, such SVGs work fine as an OpenType-SVG, as all these SVGs are used in the Pride color font at https://colorfonts.wtf/. I have included a simple reproducible example with zero.svg, from the Pride font.

```py
nanoemoji --color_format glyf_colr_1_and_picosvg ./zero.svg

I0209 18:31:05.966827 139845619483264 nanoemoji.py:611] Proceeding with 1 config(s)
I0209 18:31:05.967463 139845619483264 nanoemoji.py:569] Wrote build/Font.toml
I0209 18:31:05.967766 139845619483264 nanoemoji.py:620] Generating build.ninja
I0209 18:31:05.969572 139845619483264 nanoemoji.py:679] ninja -C /home/theel/Downloads/fonts/testcolr/build
ninja: Entering directory `/home/theel/Downloads/fonts/testcolr/build'
[1/1] /home/theel/.pyenv/versions/3.9.5/bin/python3.9 -m nanoemoji.write_font -v 0 --config_file Font.toml --fea_file Font.fea --glyphmap_file Font.glyphmap @Font.ttf.rsp
FAILED: Font.ttf 
/home/theel/.pyenv/versions/3.9.5/bin/python3.9 -m nanoemoji.write_font -v 0 --config_file Font.toml --fea_file Font.fea --glyphmap_file Font.glyphmap @Font.ttf.rsp
Traceback (most recent call last):
  File "/home/theel/Coding/nanoemoji/src/nanoemoji/write_font.py", line 767, in main
    ufo, ttfont = _generate_color_font(font_config, inputs)
  File "/home/theel/Coding/nanoemoji/src/nanoemoji/write_font.py", line 704, in _generate_color_font
    color_glyphs = tuple(
  File "/home/theel/Coding/nanoemoji/src/nanoemoji/write_font.py", line 705, in <genexpr>
    ColorGlyph.create(
  File "/home/theel/Coding/nanoemoji/src/nanoemoji/color_glyph.py", line 446, in create
    _painted_layers(
  File "/home/theel/Coding/nanoemoji/src/nanoemoji/color_glyph.py", line 316, in _painted_layers
    _paint_glyph(debug_hint, config, picosvg, context, glyph_width)
  File "/home/theel/Coding/nanoemoji/src/nanoemoji/color_glyph.py", line 249, in _paint_glyph
    color=Color.fromstring(shape.fill, alpha=shape.opacity)
  File "/home/theel/Coding/nanoemoji/src/nanoemoji/colors.py", line 219, in fromstring
    raise ValueError(f"invalid or unsupported color string: {s!r}")
ValueError: invalid or unsupported color string: 'currentColor'

<path fill="currentColor" d="M243.69,100.48 C356.13,100.61 447.251,191.73 447.371,304.17 L447.371,596.31 C447.371,708.8 356.181,799.991 243.69,799.991 C131.199,799.991 40.009,708.801 40.009,596.31 L40.009,304.17 C40.129,191.73 131.249,100.609 243.69,100.48 Z M326.44,596.341 L326.44,304.191 C326.71,274.451 310.99,246.861 285.28,231.911 C259.57,216.961 227.81,216.961 202.1,231.911 C176.39,246.861 160.68,274.451 160.95,304.191 L160.95,596.341 C161.36,641.751 198.28,678.341 243.69,678.341 C289.1,678.341 326.03,641.751 326.44,596.341 Z"/>
SVGTraverseContext(nth_of_type=0, element=<Element {http://www.w3.org/2000/svg}path at 0x7f8d260b8a00>, path='/svg[0]/path[0]', transform=Affine2D(a=1, b=0, c=0, d=1, e=0, f=0), clips=(), attrib={'fill': 'currentColor', 'clip-rule': 'nonzero', 'fill-opacity': '1', 'fill-rule': 'nonzero', 'stroke': 'none', 'stroke-dasharray': 'none', 'stroke-dashoffset': '0', 'stroke-linecap': 'butt', 'stroke-linejoin': 'miter', 'stroke-miterlimit': '4', 'stroke-opacity': '1', 'stroke-width': '1', 'style': ''})

ninja: build stopped: subcommand failed.
```
You'll notice two very wide lines. Those are, in order, `shape` and `context` (from `color_glyph._paint_glyph`). I have included them in case they help with debugging. This is the raw SVG I used as input:
```xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" viewBox="-10 0 497 1000">
   <path fill="currentColor"
      d="M 243.69 100.48
      c 112.44 0.129883 203.561 91.25 203.681 203.69
      v 292.14c0 112.49 -91.1904 203.681 -203.681 203.681
      s -203.681 -91.1904 -203.681 -203.681
      v -292.14
      c 0.120117 -112.44 91.2402 -203.561 203.681 -203.69
      z M326.44 596.341
      v -292.15
      c 0.269531 -29.7402 -15.4502 -57.3301 -41.1602 -72.2803
      s -57.4697 -14.9502 -83.1797 0
      s -41.4199 42.54 -41.1504 72.2803
      v 292.15
      c 0.410156 45.4102 37.3301 82 82.7402 82
      s 82.3398 -36.5898 82.75 -82
      z" />
</svg>
```

**Comment by rsheeter** [comment]
Good catch, that's a bug on our side. currentColor should convert to a palette index 0xFFFF (https://docs.microsoft.com/en-us/typography/opentype/spec/colr#colors-and-solid-color-fills)
