### ISSUE TITLE
SVG files that cause non-successful font build when using glyf_colr_0/glyf_colr_1 color format

### ISSUE THREAD

**Issue by DeltaRazero** [googlefonts/nanoemoji#463]
Not entirely sure what causes nanoemoji to error when building the font. Could maybe be something that Adobe Illustrator and Inkscape add some kind of data that nanoemoji doesn't seem to understand but other glyph font generators have no problem with.

Despite trying to get logging I'm only greeted with the following and I can't really seem to get actual logging out of the Ninja build process.
```
Traceback (most recent call last):
  File "/usr/local/bin/nanoemoji", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/nanoemoji/nanoemoji.py", line 761, in main
    app.run(_run)
  File "/usr/local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.10/site-packages/nanoemoji/nanoemoji.py", line 756, in _run
    maybe_run_ninja(build_file)
  File "/usr/local/lib/python3.10/site-packages/nanoemoji/ninja.py", line 125, in maybe_run_ninja
    subprocess.run(ninja_cmd, check=True)
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-C', '/tmp/glyph_fonts/2Y7Wh/build']' returned non-zero exit status 1.
```

I've attached a couple of example files that cause the exceptions. Would be nice if the issue could be looked into and subsequently a new release can be published to pypi. Surprisingly CBDT works (as that's the only other thing Chrome/Electron supports) but it's just not sharp enough since it's bitmap graphics. Haven't tested the other color format modes though.

![hpp](https://github.com/googlefonts/nanoemoji/assets/26445643/70cd3bae-25fa-437d-8175-8e340afcde71)
![nodejsLock](https://github.com/googlefonts/nanoemoji/assets/26445643/d0ac707b-e310-4791-8e2d-419a3e1acd0e)
![generatedFolder-open](https://github.com/googlefonts/nanoemoji/assets/26445643/f170b2b8-6ff7-49ba-ac39-54e578a020e2)
![Assets-open](https://github.com/googlefonts/nanoemoji/assets/26445643/3391e5e7-41ec-4568-9f3e-6d299d701c60)
![localeFolder](https://github.com/googlefonts/nanoemoji/assets/26445643/68efe4f0-56e4-4b22-a3db-22c3df394324)

Additional information:
* Using nanoemoji in a ubuntu Python docker container.
* Python 3.10.12
* nanoemoji v0.15.1
* picosvg 0.22.1

**Comment by DeltaRazero** [comment]
So after a bit of investigating it looks like it's an issue with picosvg instead since that can't seem to work with a <style> tag element. My solution is to preprocess the SVGs with SVGO and enable the `convertStyleToAttrs` and `removeStyleElement` additional to the default enabled ones to fix the issue.

There's already an ongoing issue on the picosvg repo if I'm right, so I'll just join the discussion there.

Closing the issue here, but it'd still be nice to see the picosvg output I guess to make troubleshooting easier.
