### ISSUE TITLE
colr2svg.py broken by refactor

### ISSUE THREAD

**Issue by narinishi** [googlefonts/nanoemoji#466]
colr2svg depends on a module called colr_to_svg. This used to reside under the 'tests' directory, however has since been moved to the main source folder, without colr2svg being updated.

After correcting my checked out copy for the above issue, colr2svg was able to begin execution, though failed to process the COLRv1 font I had at hand, so additional changes may be required.

**Comment by anthrotype** [comment]
> failed to process the COLRv1 font I had at hand, so additional changes may be required.

in what way?

**Comment by anthrotype** [comment]
btw, I fixed the import of colr_to_svg [here](https://github.com/googlefonts/nanoemoji/commit/fbd1a35916c2f22804a6139992d07e74480a9209) on main

**Comment by narinishi** [comment]
font used was https://github.com/googlefonts/color-fonts/blob/main/fonts/noto-glyf_colr_1.ttf

```
Traceback (most recent call last):
  File "tools\colr2svg.py", line 44, in <module>
    for glyph_name, svg in colr_to_svg(
  File "python-3.8.0-embed-amd64\nanoemoji-main\src\nanoe
moji\colr_to_svg.py", line 420, in colr_to_svg
    svgs = _colr_v1_to_svgs(view_box_callback, ttfont)
  File "python-3.8.0-embed-amd64\nanoemoji-main\src\nanoe
moji\colr_to_svg.py", line 400, in _colr_v1_to_svgs
    return {
  File "python-3.8.0-embed-amd64\nanoemoji-main\src\nanoe
moji\colr_to_svg.py", line 403, in <dictcomp>
    _colr_v1_glyph_to_svg(ttfont, glyph_set, view_box_callback, g)
  File "python-3.8.0-embed-amd64\nanoemoji-main\src\nanoe
moji\colr_to_svg.py", line 352, in _colr_v1_glyph_to_svg
    view_box, font_to_vbox = _view_box_and_transform(
  File "python-3.8.0-embed-amd64\nanoemoji-main\src\nanoe
moji\colr_to_svg.py", line 340, in _view_box_and_transform
    view_box = view_box_callback(glyph_name)
TypeError: 'Rect' object is not callable
```

**Comment by Alagong** [comment]
> font used was https://github.com/googlefonts/color-fonts/blob/main/fonts/noto-glyf_colr_1.ttf
> 
> ```
> Traceback (most recent call last):
>   File "tools\colr2svg.py", line 44, in <module>
>     for glyph_name, svg in colr_to_svg(
>   File "python-3.8.0-embed-amd64\nanoemoji-main\src\nanoemoji\colr_to_svg.py", line 420, in colr_to_svg
>     svgs = _colr_v1_to_svgs(view_box_callback, ttfont)
>   File "python-3.8.0-embed-amd64\nanoemoji-main\src\nanoemoji\colr_to_svg.py", line 400, in _colr_v1_to_svgs
>     return {
>   File "python-3.8.0-embed-amd64\nanoemoji-main\src\nanoemoji\colr_to_svg.py", line 403, in <dictcomp>
>     _colr_v1_glyph_to_svg(ttfont, glyph_set, view_box_callback, g)
>   File "python-3.8.0-embed-amd64\nanoemoji-main\src\nanoemoji\colr_to_svg.py", line 352, in _colr_v1_glyph_to_svg
>     view_box, font_to_vbox = _view_box_and_transform(
>   File "python-3.8.0-embed-amd64\nanoemoji-main\src\nanoemoji\colr_to_svg.py", line 340, in _view_box_and_transform
>     view_box = view_box_callback(glyph_name)
> TypeError: 'Rect' object is not callable
> ```

yeah, I also have this issue. how do you resolve this problem?

**Comment by anthrotype** [comment]
sorry for the late reply. Apparently this https://github.com/googlefonts/nanoemoji/commit/12a82dd427894e05529dc5e6138b0a3753887a31#diff-7b2eb8b5db3e65247e5aa74526f3fd6ab663af92b57a8aaebbbc74fcef38e43f broke the colr2svg.py script. 

We should actually get rid of that script altogether, because all its functionality (extract all COLR color glyphs to a .svg files to some output directory) should be covered by one of the internal nanoemoji subcommands (used by the maximum_color build pipeline when converting COLR to OT-SVG).

Please try to invoke it as `python -m nanoemoji.generate_svgs_from_colr --output_dir OUTPUT_DIR FONT_FILE`
